# Generated by Django 2.1.7 on 2019-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_url_shortner_app', '0003_makeshorturl_number_of_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeshorturl',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
