# Generated by Django 2.1.7 on 2019-02-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_purchased',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date purchase'),
        ),
    ]
